Step3
ADL175/pyramid-learning-journal pull request #10
Opened 2017-06-04 05:08 UTC by ADL175

2017-06-09 21:22 UTC, pasaunders requested changes
It looks like you've got the core of a decent site here. You just need to get it tested, and expand to fill the spec. I want to see the heroku deployment too.

2017-06-09 21:22 UTC, pasaunders commented on README.md
>  Step 2 w/ Carlos partnered on the journal server project. Implemented journal entries and incorporated templating to streamline user experience and refactor unnecessary code.
Good to see you keeping the readme up to date, but try to make it something that describes what your code does, not what you did to your code.

2017-06-09 21:22 UTC, pasaunders commented on README.md
>  Step 2 w/ Carlos partnered on the journal server project. Implemented journal entries and incorporated templating to streamline user experience and refactor unnecessary code.
You need a Heroku deployment link here.

2017-06-09 21:22 UTC, pasaunders commented on pyramid_learning_journal/pyramid_learning_journal/tests.py
> +    # config.add_route('detail', '/journal/{id:\d+}')
Your tests error out. Get the tests working and add a lot more. I want to see tests for expected function, expected failure, and edge cases.

2017-06-09 21:22 UTC, pasaunders commented on pyramid_learning_journal/pyramid_learning_journal/views/default.py
> +    journal = session.query(Journal).get(the_id)
Missing add and edit views. They're only supposed to return empty dictionaries right now, but they should still be here.

2017-07-13 23:42 UTC, merged

2017-07-13 23:43 UTC, ADL175 commented
fixed step3 and merged to master